### ISSUE TITLE
Becomes briefly unresponsive while submittiting command.

### ISSUE THREAD

**Issue by stuaxo** [romanvm/python-web-pdb#2]
I'm connecting to a raspberry pi over wifi, so things aren't the quickest.

It would be great if whatever is submitting the commands / redrawing was decoupled from the input box.

At the moment when I submit a command everything stops for a bit, it would seem much more responsive if I could type during this second or so.

**Comment by romanvm** [comment]
Sending commands and updating info *are* independent processes. And it's no point to type anything before a command is acknowledged because only after that the field is cleared and a successful command is stored into the command history.

But I guess I need do do some research on how Web-PDB works on high-latency setups and maybe find some solution to increase responsiveness.

**Comment by romanvm** [comment]
Please check v.1.3.0 and tell me how it works on your setup.

**Comment by stuaxo** [comment]
It certainly seems better, I only used it briefly, I need to try this for longer on the pis.

**Comment by romanvm** [comment]
Since there has been no further follow-up, I'm closing this issue.

**Comment by stuaxo** [comment]
Makes sense :)
